server:
  port: 8080
spring:
  main:
    banner-mode: "off"
  servlet:
    multipart:
      enabled: false
api:
  security:
    user: ""
    password: ""
## OneBusAway Base URL
  base-url: ${OBA_BASE_URL}
## API KEY
  key: ${API_KEY}
## Agency ID
  agency: ${AGENCY_ID}
